# docker-compose.yml  (db + backend)
services:
  db:
    image: postgres:16
    container_name: iw-postgres
    environment:
      POSTGRES_DB: insurance_workflow
      POSTGRES_USER: workflow_user
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./packages/backend
    env_file: .env
    environment:
      NODE_ENV: production
      TRUST_HTTPS: "1"
      # Point knex to the internal db service
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: insurance_workflow
      PGUSER: workflow_user
      PGPASSWORD: devpass
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  pgdata:
